OctoLinker/api

- index.js
In the last few days I saw some unresolved package like `assets/css/*.css` or `&includePaths[]=` in the logs. I don't know what's going on there, so I decided to track the request referer to get some context. The stored data are used only to improve the github-linker and will be not passed on to any third party.
> Track referer if package was not found

- src/resolver/composer.js
- test/resolver-composer.spec.js
If the composer lookup fails, link to `https://packagist.org/packages/{vendor}/{client}`
> Packagist fallback for Composer

- src/plugins/universal-resolver.js
- test/universal-resolver.spec.js
For example, https://githublinker.herokuapp.com/q/npm/@angular/core
doesn't work, but it will with this patch.
> Resolve scoped packages like @angular/core

- config.json
In favor of add Python support https://github.com/OctoLinker/browser-extension/issues/33 this addition is needed.
> Add pypi support

- README.md
- config.json
This is needed for https://github.com/OctoLinker/browser-extension/issues/45
> Add support for Rust crates

- package.json
- src/utils/repository-url.js
- test/functional.js
- test/repository-url.spec.js
This will make it so `babel-*` packages like `babel-helper-regex` will
correctly link to e.g.
https://github.com/babel/babel/tree/master/packages/babel-helper-regex
instead of https://github.com/babel/babel/. See the commit messages for
more details.
> Add support for GitHub URLs containing paths

- src/plugins/universal-resolver.js
- test/functional.js
fixes https://github.com/OctoLinker/browser-extension/issues/287
> Make npm links fallback to npmjs.org if repo url 404s

- config.json
- test/functional.js
npmjs.org does a 301 redirect to www.npmjs.com, so just go directly there
instead. For example: https://npmjs.org/package/audio-context-polyfill
> npm: fallback to www.npmjs.com instead of npmjs.org

- npm-shrinkwrap.json
- package.json
- server.js
- src/plugins/go-resolver.js
- test/functional.js
The key to get custom import working is in the <meta> tag named `go-import`. When requesting https://k8s.io/kubernetes/pkg/api we know that `k8s.io/kubernetes/pkg/api` points to https://github.com/kubernetes/kubernetes/tree/master/pkg/api.
[http://localhost:3000/q/go/k8s.io/kubernetes/pkg/api](http://localhost:3000/q/go/k8s.io/kubernetes/pkg/api)
[http://localhost:3000/q/go/code.gitea.io/gitea/modules/setting](http://localhost:3000/q/go/code.gitea.io/gitea/modules/setting)
https://github.com/OctoLinker/browser-extension/issues/264
> Fetch repo from custom go import path

- src/plugins/go-resolver.js
EDIT: This is best reviewed ignoring whitespace: https://github.com/OctoLinker/live-resolver/pull/30/files?&w=true
> go-resolver: Use `await` to simplify `getGoMeta`

- test/functional.js
Note that mocha allows test functions to return a promise instead of
calling a `done` callback. Since the `async` keyword causes a promise to
be returned, we don't need to call `done` (in fact, it is an error to).
https://mochajs.org/#working-with-promises
EDIT: best reviewed ignoring whitespace: https://github.com/OctoLinker/live-resolver/pull/31/files?&w=true
> Use async/await in tests

- package.json
This allows newer Node versions to be used.
> package.json: Specify Node ^7.6.0 as engine

- .travis.yml
c410ff4 (#38) caused the heroku [deploy] to use Node v7.7.4 instead of
v7.6.0, so let's make sure to test on the latest Node as well.
[deploy]: https://travis-ci.org/OctoLinker/live-resolver/builds/215311723#L386-L387
> Travis: test on latest Node v7

- package.json
- src/plugins/go-resolver.js
- src/utils/do-request.js
- yarn.lock
In the previous version of [`find-reachable-urls`](https://github.com/stefanbuck/find-reachable-urls) the callback was invoked after all urls have been checked. Sometimes it takes very long to complete all requests. With version`1.1.1` you can claim your interest in the first reachable url which will stop any further requests.
> Bump find-reachable-urls to 1.1.1

- test/functional.js
The package buble moved to github which let the functional tests fail.
Also I think there is no value for testing projects hosted on different hosting
sites. Live resolver reads the url from the package.json regardless what the value is
> remove functional test for buble

- package.json
- server.js
- src/plugins/go-resolver.js
- src/plugins/home.js
- src/plugins/java-resolver.js
- src/plugins/melpa-resolver.js
- src/plugins/ping.js
- src/plugins/universal-resolver.js
- src/utils/do-request.js
- test/functional.js
- test/ping.spec.js
- test/universal-resolver.spec.js
- yarn.lock
As you might have noticed, Hapi with version 17 has recently moved to using async/await. This requires breaking changes. Luckily it was quite simple in our case. All Hapi related dependencies have also been updated to the latest versions.
Fix #51
> Changes required to use Hapi 17

- package.json
- server.js
- src/plugins/bulk.js
- test/functional.js
- yarn.lock
Towards our mission to use real links (see https://github.com/OctoLinker/OctoLinker/issues/277), this PR adds a new bulk endpoint to our service. This is needed to reduce response times and server load when prefetching links for the OctoLinker browser extension. 
The order of the response is equal to the order in request body. If a query fails or can't be resolved the api will return `null`. 
```json
[
{
"type": "registry",
"registry": "npm",
"target": "request"
},
{
"type": "ping",
"target": "https://nodejs.org/api/path.html"
},
{
"type": "registry",
"registry": "npm",
"target": "package_which_does_not_exist"
}
]
```
```json
[
"https://github.com/request/request",
"https://nodejs.org/api/path.html",
null
]
```
> Add bulk endpoint

- src/plugins/melpa-resolver.js
Now that `got` no longer throws an error for 304 responses, we don't
need to check the status code. See here for details/context:
https://github.com/OctoLinker/live-resolver/pull/60#issuecomment-377801405
> melpa-resolve: Simplify 304 handling

- package.json
- src/utils/insight.js
- yarn.lock
The problem is that keen-dataviz.js uses c3.js. We don't use chart so in our case the solution is to install keen-tracking and remove keen-js.
> Use keen-tracking to make jest working

- server.js
Although this information exists in the server logs I think using keen.io has some advantages. First of all, logs aren't a good place to store data for a long term. Also Heroku caps the logs so we can only see a small range. With the recently added bulk endpoint we will get much more traffic on this service soon. Therefore I would like to be able to see restarts over a longer time period.
> Store service start in keen.io

- package.json
- src/plugins/go-resolver.js
- src/plugins/melpa-resolver.js
- src/plugins/ping.js
- src/plugins/universal-resolver.js
- src/utils/memRequest.js
- test/ping.spec.js
- yarn.lock
Three years ago, I implemented caching to speed up the service 8607b5f31c5db81499aaf7bba9ee6732fc53d0dd. Last week I noticed that his isn't in place anymore. Looks like I removed it 198c23fc33cbaedf047eae36df87607c6862037d.
With the upcoming refactoring of the browser extension the load on the service will increase dramatically. Therefore we need a solid caching in place. I added [mem](https://github.com/sindresorhus/mem) to cache the responses in memory. 
The implementation was straight forward. There is only thing I didn't like. In `ping.js` I had to wrap the `got` module in another file to make the stub working. @josephfrazier if you have any better way to solve this, please let me know.
> Fix / add caching

- src/plugins/ping.js
- test/ping.spec.js
For some reason a HTTP GET request sneaked in when making a ping request. A HEAD request is the appropriate way to reduce the request size.
> Perform HEAD request for ping requests

- src/utils/insight.js
A value of `0` means that the user prefers to allow tracking on the target site.
A value of `1` means the user prefers not to be tracked on the target site.
If the DNT header is missing or the value is not defined, we will track this request.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT for details
> Implement DNT header

- README.md
- src/utils/insight.js
Yesterday, a new version of OctoLinker was released with the option to opt-out of logging. Today, I noticed that this isn't working as expected. Setting `DNT: 1` cause the browser to throw the following error.
```
Refused to set unsafe header DNT
```
I'm not 100% sure why I can't set this header, but I worked around by introducing a custom header called `do-not-track`.
> Use custom header to avoid clash with the DNT standard

- src/plugins/go-resolver.js
When requesting https://githublinker.herokuapp.com/q/go/k8s.io/kubernetes/pkg/api it responds with `{"url":"https://github.com/kubernetes/kubernetes\n"}` which should be`{"url":"https://github.com/kubernetes/kubernetes/tree/master/pkg/api"}` 
A `curl` of `https://k8s.io/kubernetes/pkg/api\?go-get\=1` shows a few white spaces and new lines within the `<meta name="go-source" content="....`
```html
<html><head>
<meta name="go-import"
content="k8s.io/kubernetes
git https://github.com/kubernetes/kubernetes">
<meta name="go-source"
content="k8s.io/kubernetes
https://github.com/kubernetes/kubernetes
https://github.com/kubernetes/kubernetes/tree/master{/dir}
https://github.com/kubernetes/kubernetes/blob/master{/dir}/{file}#L{line}">
</head></html>
```
After taking all whitespace (spaces, tabs and …
> Strip multiple spaces from go-source meta tag

- package.json
- src/plugins/go-resolver.js
- src/plugins/melpa-resolver.js
- src/plugins/ping.js
- src/plugins/universal-resolver.js
- src/utils/cache.js
- src/utils/do-request.js
- src/utils/memRequest.js
- test/ping.spec.js
- yarn.lock
The mem package was a quite simple solution to add caching in the first place. Now with more traffic on the service a caching strategy that supports ttl is needed to maintain a healthy memory consumption. [receptacle](https://www.npmjs.com/package/receptacle) looks pretty good for this job. Btw this PR is already running in production since yesterday so it's already battle tested.
> New caching strategy

- src/plugins/universal-resolver.js
- test/functional.spec.js
My previous PR #77 introduced an issue when resolving packages from the static cache file. The response format needs to be a JSON like`{ url: 'http://' }`, but instead just an URL string was returned. We didn't catch this earlier, because non of our functional tests was querying a package from the cache file.
> When resolving with a cache result respond with json format

- .gitignore
- functional.spec.js
- src/java/index.js
- src/utils/cache.js
Before java standard library were resolved through the ping plugin. This plugin was called with different possible url combinations which caused an unnecessary delay. By using `find-reachable-urls` the first url which response with 200 will be returned.
> Resolve java standard libraries through java resolver

- README.md
- devserver.js
- package.json
Working on this service without using `now dev` is not that straight forward and requires creating a server yourself. This Pull Requests adds `npm run dev` which spins up a local dev-server using the Node.js build-in `http` module and `nodemon` for auto refresh.
> Add dev server for local development

- README.md
- functional.spec.js
- src/registries/config.json
@xt0rted started working on adding Dart support to OctoLinker and this is the counter part to resolve Dart dependencies using the OctoLinker API.
Preview https://octolinker-api-git-support-pub.octolinker1.now.sh/?pub=connectivity
> Add support for pub.dev registry

- .github/workflows/ci.yml
- README.md
- functional.spec.js
- src/handler.js
- src/registries/config.json
- src/registries/index.js
- src/utils/url.js
- src/utils/url.spec.js
Add `cran` to support as outlined in #252 
Example:
https://octolinker-api-git-cran-support.octolinker1.vercel.app/?cran=usethis
> Add cran support

- .gitattributes
- functional.spec.js
- package-lock.json
- package.json
- src/handler.js
- src/nuget.js
- src/utils/payload.js
This is using optional chaining which works in node 14+ from what I can tell, so we might need to increase the node version the api runs on, or refactor the code so it doesn't use that feature.
Version endpoint: https://api.nuget.org/v3-flatcontainer/qrcoder/index.json
Package endpoint: https://api.nuget.org/v3-flatcontainer/qrcoder/1.3.9/qrcoder.nuspec
> Add nuget support

- src/ping.js
- src/registries/index.js
- src/utils/cache.js
- src/utils/cache.spec.js
Increase cache TTL from 12 hours to 48 hours. Unresolved pings were cached 15min, now also 48 hours. This change is required to reduce the serverless invocation time which is noticeable high right now.
> Reduce severless execution time by increasing cache duration
