OctoLinker/api

package.json
plugins/home.js
plugins/ping.js
plugins/universal-resolver.js
server.js
src/utils/insight.js
test/ping.spec.js
test/universal-resolver.spec.js

Add route which helps to determine if an url is available or not. It will respond with a 200 response if the HTTP HEAD request was successfully, otherwise it returns 500.
**Example:**
https://githublinker.herokuapp.com/ping?url=http://www.nodejs.org

Add ping route

---

README.md
config.json
package.json

Allows you to request the github repository for a rubygems project.
https://githublinker.herokuapp.com/q/rubygems/nanoc

Add rubygems support

---

src/plugins/universal-resolver.js
test/universal-resolver.spec.js

Resolves https://github.com/OctoLinker/browser-extension/issues/110

Use fallback url when no repo url is found

---

server.js
test/functional.js

These start a server and look up a popular package on each supported
registry. If the server does not give the expected response with 2
seconds (the [default](https://mochajs.org/#t---timeout-ms) mocha timeout for async tests), the test will fail.
See https://github.com/OctoLinker/live-resolver/pull/17#issuecomment-237968870

Add functional tests

---

npm-shrinkwrap.json
package.json

This PR updates nodejs to v7.5.0, dev and prod dependencies and adds a shrinkwrap file.

Update dependencies and nodejs version

---

src/plugins/universal-resolver.js
src/utils/do-request.js

This makes it easier to use on its own, as suggested in
https://github.com/OctoLinker/browser-extension/issues/280#issuecomment-279037295

Move doRequest() into its own file in utils/

---

src/plugins/universal-resolver.js
src/utils/do-request.js

After this and the following are merged, there won't be any more
callbacks or explicit promises in the code :)
* https://github.com/OctoLinker/live-resolver/pull/30
* https://github.com/OctoLinker/live-resolver/pull/31
* https://github.com/OctoLinker/live-resolver/pull/32

Use async/await in doRequest/universal-resolver

---

package.json
test/functional.js
yarn.lock

This halves the test duration on my machine.

Run functional tests in parallel

---

server.js
src/plugins/melpa-resolver.js
test/functional.js

As discussed with @benjamreynolds in https://github.com/OctoLinker/browser-extension/issues/212,
this makes it possible to use `/q/melpa/{package}` to get the URL from
https://melpa.org/archive.json.

Add MELPA resolver

---

package.json
yarn.lock

Upgrade hapi and a few other dependencies.

Bump various  dependencies

---

config.json
package.json
test/universal-resolver.spec.js

also I had to update the bower registry url, because of failing tests

Use node LTS version 8.9.0

---

src/utils/do-request.js
test/functional.js

This can help in cases where the repo exists, but isn't referenced in
package.json.
See here for more information about the npm registry API response fields:
https://github.com/npm/registry/blob/51b9a9467a63cc4a4929590a7044e2612377c102/docs/responses/package-metadata.md

npm: Guess that the repo might be $maintainerUsername/$packageName

---

yarn.lock

Fixes https://nodesecurity.io/advisories/566

Upgrade dependencies with `yarn upgrade`

---

.travis.yml
package.json
src/utils/insight.js
yarn.lock

see https://hapijs.com/updates

Update hapi to the latest version

---

.eslintrc.json
package.json
src/plugins/bulk.js
src/plugins/java-resolver.js
test/config.spec.js
test/functional.js
test/functional.spec.js
test/ping.spec.js
test/repository-url.spec.js
test/universal-resolver.spec.js
test/xpath-helper.spec.js
yarn.lock

Nothing more to add 😉 
Update:
I had problems with `require-dir` in the new jest environment. Using `require-directory` seems to fix this. See https://github.com/aseemk/requireDir/issues/53#issuecomment-371952522 for details

Replace mocha with Jest

---

.travis.yml
package.json

Use node 10

---

package.json
yarn.lock

Update various dependencies

---

src/plugins/universal-resolver.js

Well, I know why I prefer to get a code review on every PR 😉

Apply npm cache for npm and bower requests

---

src/handler.js

See https://zeit.co/blog/serverless-pre-rendering

Use Pre-rendering

---

README.md

I forgot to update the readme in #261 😔

Add nuget to the readme

---

.github/workflows/ci.yml
package.json

Update to node.js 14 so we can use es6 modules which is needed to merge #316

Update to node.js 14
